# Generated by Django 4.0.4 on 2022-08-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.FileField(default=None, max_length=255, null=True, upload_to='news/'),
        ),
    ]
