# Generated by Django 4.0.4 on 2022-08-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=255)),
                ('en_email', models.EmailField(max_length=255)),
                ('en_phone', models.BigIntegerField(max_length=11)),
                ('en_message', models.TextField()),
            ],
        ),
    ]
