# Generated by Django 4.0.4 on 2022-08-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='en_phone',
            field=models.BigIntegerField(),
        ),
    ]
