# Generated by Django 4.2 on 2023-05-28 16:44

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialLink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='sl_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='sl_name', unique=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='sl_icon',
            field=models.FileField(default=None, max_length=255, null=True, upload_to='social/'),
        ),
    ]
